# Calculating the amount spent by each costumer

We have a dataset where different costumers have bought items at different times. We'll be aggregating the price of all those items in order to find out who spends the most.

In [19]:
def extractCostumerPricePair(line):
    fields = line.split(',')
    return(int(fields[0]), float(fields[2]))

input = sc.textFile('/Users/jacquesthibodeau/big-data-datasets/customer-orders.csv')
parsedLines = input.map(extractCostumerPricePair)

totalByCostumer = parsedLines.mapValues(lambda x: (x, 1)).reduceByKey(lambda x, y: (x + y))
sortedAmountByCostumer = amountByCostumer.sortByKey()

results = sortedAmountByCostumer.collect()

for result in results:
    print(result[0], round(result[1], 2))

0 5524.95
1 4958.6
2 5994.59
3 4659.63
4 4815.05
5 4561.07
6 5397.88
7 4755.07
8 5517.24
9 5322.65
10 4819.7
11 5152.29
12 4664.59
13 4367.62
14 4735.03
15 5413.51
16 4979.06
17 5032.68
18 4921.27
19 5059.43
20 4836.86
21 4707.41
22 5019.45
23 4042.65
24 5259.92
25 5057.61
26 5250.4
27 4915.89
28 5000.71
29 5032.53
30 4990.72
31 4765.05
32 5496.05
33 5254.66
34 5330.8
35 5155.42
36 4278.05
37 4735.2
38 4898.46
39 6193.11
40 5186.43
41 5637.62
42 5696.84
43 5368.83
44 4756.89
45 3309.38
46 5963.11
47 4316.3
48 4384.33
49 4394.6
50 4517.27
51 4975.22
52 5245.06
53 4945.3
54 6065.39
55 5298.09
56 4701.02
57 4628.4
58 5437.73
59 5642.89
60 5040.71
61 5497.48
62 5253.32
63 5415.15
64 5288.69
65 5140.35
66 4681.92
67 4505.79
68 6375.45
69 5123.01
70 5368.25
71 5995.66
72 5337.44
73 6206.2
74 4647.13
75 4178.5
76 4904.21
77 4327.73
78 4524.51
79 3790.57
80 4727.86
81 5112.71
82 4812.49
83 4635.8
84 4652.94
85 5503.43
86 4908.81
87 5206.4
88 4830.55
89 4851.48
90 5290.41
91 4642.26
92 5379.28
93 5265.75
94 4475.57
95 4876.84
96 3924.23
97 5977.19
98 4297.26
99 4172.29

We will now sort by the amount spent in order to clearly see who spends the most.

In [20]:
sortedByAmountSpent = sortedAmountByCostumer.map(lambda x: (x[1], x[0])).sortByKey(ascending=False)

results = sortedByAmountSpent.collect()

for result in results:
    print(round(result[0], 2), result[1])

6375.45 68
6206.2 73
6193.11 39
6065.39 54
5995.66 71
5994.59 2
5977.19 97
5963.11 46
5696.84 42
5642.89 59
5637.62 41
5524.95 0
5517.24 8
5503.43 85
5497.48 61
5496.05 32
5437.73 58
5415.15 63
5413.51 15
5397.88 6
5379.28 92
5368.83 43
5368.25 70
5337.44 72
5330.8 34
5322.65 9
5298.09 55
5290.41 90
5288.69 64
5265.75 93
5259.92 24
5254.66 33
5253.32 62
5250.4 26
5245.06 52
5206.4 87
5186.43 40
5155.42 35
5152.29 11
5140.35 65
5123.01 69
5112.71 81
5059.43 19
5057.61 25
5040.71 60
5032.68 17
5032.53 29
5019.45 22
5000.71 28
4990.72 30
4979.06 16
4975.22 51
4958.6 1
4945.3 53
4921.27 18
4915.89 27
4908.81 86
4904.21 76
4898.46 38
4876.84 95
4851.48 89
4836.86 20
4830.55 88
4819.7 10
4815.05 4
4812.49 82
4765.05 31
4756.89 44
4755.07 7
4735.2 37
4735.03 14
4727.86 80
4707.41 21
4701.02 56
4681.92 66
4664.59 12
4659.63 3
4652.94 84
4647.13 74
4642.26 91
4635.8 83
4628.4 57
4561.07 5
4524.51 78
4517.27 50
4505.79 67
4475.57 94
4394.6 49
4384.33 48
4367.62 13
4327.73 77
4316.3 47
4297.26 98
4278.05 36
4178.5 75
4172.29 99
4042.65 23
3924.23 96
3790.57 79
3309.38 45